### ISSUE TITLE
v.2.2.1 On FireTV tiles cannot be selected

### ISSUE THREAD

**Issue by tomybec** [leonardoxh/race-control-tv#85]
When you go into season 2021, or any other season, you cannot select which video to play.
The tiles move to the left as you press to the right, but no tile can be selected and played.

Previously used version 2.1.1 where it was fine.
Cleared data, uninstalled it, installed 2.2.1

If you need any more feedback, please ask.
Thank you for your time and the great work, well done!

**Comment by leonardoxh** [comment]
Can you record a video of your issue?

**Comment by tomybec** [comment]
Here you are.
Best regards!

https://user-images.githubusercontent.com/68645590/126539869-f0b7efaf-5b20-4967-a41a-eb4d10831093.mp4

**Comment by junocloud** [comment]
Hey, just finished updating and now I have this same problem.

**Comment by leonardoxh** [comment]
Hi guys, could you join the Alpha program test to help me with this issue? I just released a build there that should be available in some minutes aiming to solve this issue

Click this link on web to join the Alpha program: https://play.google.com/apps/testing/com.github.leonardoxh.f1 (If you installed the app via Google PlayStore)

**Comment by junocloud** [comment]
Hello,
I just installed the new version 2.2.2, but i still have the same problem.

I can't join the Alpha program for some reason..

The app is not available for this account.
Your account is currently not eligible for this app's testing program.

**Comment by leonardoxh** [comment]
Hmmmmmmmmm If you were not available to join the alpha program how did you install it? You compiled from the branch itself?

**Comment by junocloud** [comment]
I sideloaded through the Downloader app on the Fire TV Stick.

**Comment by leonardoxh** [comment]
You sure it is v2.2.2 ? Because I did not publish it yet...

By the way, can you try to side load this apk:
https://github.com/leonardoxh/race-control-tv/releases/tag/v2.2.3

I did some other changes, I might just found something.

**Comment by junocloud** [comment]
Now i cant enter any of the menus, when i choose a season, it briefly loads and return to choose a season again.

**Comment by ruppy99** [comment]
Tried 2.2.3. Tries the load the current season, fails and returns to season selection screen

**Comment by leonardoxh** [comment]
Oh god apologies.

Wrong apk, can you please try with this one?
https://github.com/leonardoxh/race-control-tv/releases/tag/v2.2.4

**Comment by junocloud** [comment]
Ok, now i can play the videos, but i can't see what i am choosing, the indicator of what is selected is gone.

**Comment by leonardoxh** [comment]
Cool that is good at least, I will see this tomorrow

**Comment by leonardoxh** [comment]
Hi I think I got it, had to revert more stuff from another PR.

I uploaded the apk to my google drive this time to avoid create another release, if it is working I will then release it

https://drive.google.com/file/d/1Qr6nE-E8QWGRFeNUWDZD9YUdXZ_1xFpF/view?usp=sharing

**Comment by junocloud** [comment]
Hey there, the 2.2.5 has the same issue, i can play the videos, but can't see what is selected.

**Comment by leonardoxh** [comment]
What about this one?

It will still show as v2.2.5

**Comment by junocloud** [comment]
This one is good! Working fine now.

**Comment by leonardoxh** [comment]
Fantastic I will publish it right away.

**Comment by leonardoxh** [comment]
Thank you very much for the testing and patience. I released v2.2.5

Closing this issue for now
